//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Keysticks.WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="KeysticksWebServiceBinding", Namespace="https://keysticks.net/")]
    public partial class KeysticksWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckForumUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProgramUpdatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProfilesListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProfileDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWordPredictionLanguagePackOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteProfileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public KeysticksWebService() {
            this.Url = global::Keysticks.Properties.Settings.Default.Keysticks_KeysticksWebService_KeysticksWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckForumUserCompletedEventHandler CheckForumUserCompleted;
        
        /// <remarks/>
        public event GetProgramUpdatesCompletedEventHandler GetProgramUpdatesCompleted;
        
        /// <remarks/>
        public event GetProfilesListCompletedEventHandler GetProfilesListCompleted;
        
        /// <remarks/>
        public event GetProfileDataCompletedEventHandler GetProfileDataCompleted;
        
        /// <remarks/>
        public event GetWordPredictionLanguagePackCompletedEventHandler GetWordPredictionLanguagePackCompleted;
        
        /// <remarks/>
        public event SubmitProfileCompletedEventHandler SubmitProfileCompleted;
        
        /// <remarks/>
        public event DeleteProfileCompletedEventHandler DeleteProfileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/keysticks/webservices/KxSoapServer.php/CheckForumUser", RequestNamespace="", ResponseNamespace="")]
        public string CheckForumUser(string request) {
            object[] results = this.Invoke("CheckForumUser", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckForumUserAsync(string request) {
            this.CheckForumUserAsync(request, null);
        }
        
        /// <remarks/>
        public void CheckForumUserAsync(string request, object userState) {
            if ((this.CheckForumUserOperationCompleted == null)) {
                this.CheckForumUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckForumUserOperationCompleted);
            }
            this.InvokeAsync("CheckForumUser", new object[] {
                        request}, this.CheckForumUserOperationCompleted, userState);
        }
        
        private void OnCheckForumUserOperationCompleted(object arg) {
            if ((this.CheckForumUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckForumUserCompleted(this, new CheckForumUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/keysticks/webservices/KxSoapServer.php/GetProgramUpdates", RequestNamespace="", ResponseNamespace="")]
        public string GetProgramUpdates(string request) {
            object[] results = this.Invoke("GetProgramUpdates", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetProgramUpdatesAsync(string request) {
            this.GetProgramUpdatesAsync(request, null);
        }
        
        /// <remarks/>
        public void GetProgramUpdatesAsync(string request, object userState) {
            if ((this.GetProgramUpdatesOperationCompleted == null)) {
                this.GetProgramUpdatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProgramUpdatesOperationCompleted);
            }
            this.InvokeAsync("GetProgramUpdates", new object[] {
                        request}, this.GetProgramUpdatesOperationCompleted, userState);
        }
        
        private void OnGetProgramUpdatesOperationCompleted(object arg) {
            if ((this.GetProgramUpdatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProgramUpdatesCompleted(this, new GetProgramUpdatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/keysticks/webservices/KxSoapServer.php/GetProfilesList", RequestNamespace="", ResponseNamespace="")]
        public string GetProfilesList(string request) {
            object[] results = this.Invoke("GetProfilesList", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetProfilesListAsync(string request) {
            this.GetProfilesListAsync(request, null);
        }
        
        /// <remarks/>
        public void GetProfilesListAsync(string request, object userState) {
            if ((this.GetProfilesListOperationCompleted == null)) {
                this.GetProfilesListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProfilesListOperationCompleted);
            }
            this.InvokeAsync("GetProfilesList", new object[] {
                        request}, this.GetProfilesListOperationCompleted, userState);
        }
        
        private void OnGetProfilesListOperationCompleted(object arg) {
            if ((this.GetProfilesListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProfilesListCompleted(this, new GetProfilesListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/keysticks/webservices/KxSoapServer.php/GetProfileData", RequestNamespace="", ResponseNamespace="")]
        public string GetProfileData(string request) {
            object[] results = this.Invoke("GetProfileData", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetProfileDataAsync(string request) {
            this.GetProfileDataAsync(request, null);
        }
        
        /// <remarks/>
        public void GetProfileDataAsync(string request, object userState) {
            if ((this.GetProfileDataOperationCompleted == null)) {
                this.GetProfileDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProfileDataOperationCompleted);
            }
            this.InvokeAsync("GetProfileData", new object[] {
                        request}, this.GetProfileDataOperationCompleted, userState);
        }
        
        private void OnGetProfileDataOperationCompleted(object arg) {
            if ((this.GetProfileDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProfileDataCompleted(this, new GetProfileDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/keysticks/webservices/KxSoapServer.php/GetWordPredictionLanguage" +
            "Pack", RequestNamespace="", ResponseNamespace="")]
        public string GetWordPredictionLanguagePack(string request) {
            object[] results = this.Invoke("GetWordPredictionLanguagePack", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetWordPredictionLanguagePackAsync(string request) {
            this.GetWordPredictionLanguagePackAsync(request, null);
        }
        
        /// <remarks/>
        public void GetWordPredictionLanguagePackAsync(string request, object userState) {
            if ((this.GetWordPredictionLanguagePackOperationCompleted == null)) {
                this.GetWordPredictionLanguagePackOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWordPredictionLanguagePackOperationCompleted);
            }
            this.InvokeAsync("GetWordPredictionLanguagePack", new object[] {
                        request}, this.GetWordPredictionLanguagePackOperationCompleted, userState);
        }
        
        private void OnGetWordPredictionLanguagePackOperationCompleted(object arg) {
            if ((this.GetWordPredictionLanguagePackCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWordPredictionLanguagePackCompleted(this, new GetWordPredictionLanguagePackCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/keysticks/webservices/KxSoapServer.php/SubmitProfile", RequestNamespace="", ResponseNamespace="")]
        public string SubmitProfile(string request) {
            object[] results = this.Invoke("SubmitProfile", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitProfileAsync(string request) {
            this.SubmitProfileAsync(request, null);
        }
        
        /// <remarks/>
        public void SubmitProfileAsync(string request, object userState) {
            if ((this.SubmitProfileOperationCompleted == null)) {
                this.SubmitProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitProfileOperationCompleted);
            }
            this.InvokeAsync("SubmitProfile", new object[] {
                        request}, this.SubmitProfileOperationCompleted, userState);
        }
        
        private void OnSubmitProfileOperationCompleted(object arg) {
            if ((this.SubmitProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitProfileCompleted(this, new SubmitProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/keysticks/webservices/KxSoapServer.php/DeleteProfile", RequestNamespace="", ResponseNamespace="")]
        public string DeleteProfile(string request) {
            object[] results = this.Invoke("DeleteProfile", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteProfileAsync(string request) {
            this.DeleteProfileAsync(request, null);
        }
        
        /// <remarks/>
        public void DeleteProfileAsync(string request, object userState) {
            if ((this.DeleteProfileOperationCompleted == null)) {
                this.DeleteProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteProfileOperationCompleted);
            }
            this.InvokeAsync("DeleteProfile", new object[] {
                        request}, this.DeleteProfileOperationCompleted, userState);
        }
        
        private void OnDeleteProfileOperationCompleted(object arg) {
            if ((this.DeleteProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteProfileCompleted(this, new DeleteProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void CheckForumUserCompletedEventHandler(object sender, CheckForumUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckForumUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckForumUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetProgramUpdatesCompletedEventHandler(object sender, GetProgramUpdatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProgramUpdatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProgramUpdatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetProfilesListCompletedEventHandler(object sender, GetProfilesListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProfilesListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProfilesListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetProfileDataCompletedEventHandler(object sender, GetProfileDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProfileDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProfileDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void GetWordPredictionLanguagePackCompletedEventHandler(object sender, GetWordPredictionLanguagePackCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWordPredictionLanguagePackCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWordPredictionLanguagePackCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SubmitProfileCompletedEventHandler(object sender, SubmitProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void DeleteProfileCompletedEventHandler(object sender, DeleteProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591